email: email@domain.com
password: yourpassword

disableAntiLock: False

remote: True

experienceLevel:
 internship: False
 entry: True
 associate: True
 mid-senior level: True
 director: False
 executive: False

jobTypes:
 full-time: True
 contract: True
 part-time: False
 temporary: True
 internship: False
 other: False
 volunteer: False

date:
 all time: True
 month: False
 week: False
 24 hours: False

positions:
 #- First position
 #- A second position
 #- A third position
 #- ...
locations:
 #- First location
 #- A second location
 #- A third location
 - Los Angeles, California
 - Remote

distance: 50

companyBlacklist:
 #- company
 #- company2

titleBlacklist:
 #- word1
 #- word2

posterBlacklist:
 #- name1
 #- name2

# ------------ Additional parameters: personal info ---------------
personalInfo:
 First Name: Suleman
 Last Name: Imdad
 Phone Country Code: United States (+1)              # See linkedin for your country code, must be exact according to the international platform, i.e. Italy (+39) not Italia (+39)
 Mobile Phone Number: 4086017007
 Street address: 13836 Bora Bora Way Apt 217
 City: Marina Del Rey                      # Include the state/province as well!
 State: CA
 Zip: 90292
 Linkedin: https://www.linkedin.com/in/suleman-imdad
 Website: https://www.apportunity.io          # github/website is interchangeable here
